services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-CU20-ubuntu-22.04
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "1q2w3e4r@#$"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data: